numero = int(input("Digite um número para ver sua tabuada: "))

print(f"{numero} x {0:2} = {numero*0}")
print(f"{numero} x {1:2} = {numero*1}")
print(f"{numero} x {2:2} = {numero*2}")
print(f"{numero} x {3:2} = {numero*3}")
print(f"{numero} x {4:2} = {numero*4}")
print(f"{numero} x {5:2} = {numero*5}")
print(f"{numero} x {6:2} = {numero*6}")
print(f"{numero} x {7:2} = {numero*7}")
print(f"{numero} x {8:2} = {numero*8}")
print(f"{numero} x {9:2} = {numero*9}")
print(f"{numero} x {10:2} = {numero*10}")
